language: generic 
arch:     amd64 
os:       linux  
dist:     focal  
services:
  - docker

before_install:
  - docker build -t eggressive/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true eggressive/docker-react npm run test
